name: Generate Snake
on:
  schedule: # execute every 12 hours
    - cron: "* */24 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif

        with:
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=green&color_dots=#bfd6f6,#fff87a,#f1fa50,#eded2f,#d6d027
          github_user_name: ${{ github.repository_owner }}
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
